### ISSUE TITLE
Avoid registering exporters at the init function

### ISSUE THREAD

**Issue by kpacha** [krakend/krakend-opencensus#31]
... so a context can be passed to the exporter

**Comment by breml** [comment]
@kpacha Thanks for opening the issue.

A quick updated from my end: we ended up replacing this package in our KrakenD API GW with our own implementation for the prometheus metrics, as we are currently only interested in the prometheus metrics part of opencensus.
After fixing #28 and #30 still have not been able to get our existing test suite running with this package in place, because of the global state and the `init()` functions. The problem boils down to us starting and stopping the Krakend based API GW multiple times during our test-suite, which conflicted heavily with the global state introduced by this package (we had panics and nil pointer exceptions). The reason for this are mostly the metrics collectors being registered multiple times.

The above mentioned "context can be passed to the exporter" was less of a problem for us.

**Comment by suadev** [comment]
hi @breml, I am looking for a grafana dashboard to visualize my prometheus metrics. There is a great dashboard for influxdb [here](https://grafana.com/grafana/dashboards/5722) but not able to find on for prometheus.  

Just wanted to ask did you use grafana or something else for creating useful dashboards. Thanks.

**Comment by breml** [comment]
Hi @suadev, we used Grafana for the visualization of the results. That being said, I have no longer access to these dashboards.

**Comment by suadev** [comment]
Thank you for you response @breml 

It looks like we need to create our grafana dashboards from scratch :/  

or maybe @kpacha and @alombarte may know where I can find one?  ( sorry for mention guys )

**Comment by alombarte** [comment]
Hello,

Thank you for opening this issue. KrakenD has traditionally offered its telemetry integration through this OpenCensus component, which has provided reliable service for over six years, but it is now transitioning to the more modern and robust [OpenTelemetry framework](https://www.krakend.io/docs/telemetry/opentelemetry/), including the **Prometheus dashboard** @suadev .

Due to a change in the industry, the OpenCensus integration is no longer maintained by its creators, and all efforts are focused on OpenTelemetry. KrakenD shifted to OTEL too.

Issues found with OTEL can be opened in the repository [krakend-otel](https://github.com/krakend/krakend-otel)

Thank you
