### ISSUE TITLE
Support Jager GRPC Export

### ISSUE THREAD

**Issue by L3tum** [krakend/krakend-opencensus#50]
Hey, would it be possible to support the GRPC Exporter for Jager?

Here's a link to the [config](https://github.com/census-ecosystem/opencensus-go-exporter-jaeger/blob/master/jaeger.go#L51). I'm not sure if this works in here? I find the opencensus libraries very confusing honestly, albeit sadly without really an alternative.

**Comment by alombarte** [comment]
Hello,

Thank you for opening this issue. KrakenD has traditionally offered its telemetry integration through this OpenCensus component, which has provided reliable service for over six years, but it is now transitioning to the more modern and robust [OpenTelemetry framework](https://www.krakend.io/docs/telemetry/opentelemetry/), which includes gRPC export for jaeger.

Due to a change in the industry, the OpenCensus integration is no longer maintained by its creators, and all efforts are focused on OpenTelemetry. KrakenD shifted to OTEL too.

Issues found with OTEL can be opened in the repository [krakend-otel](https://github.com/krakend/krakend-otel)

Thank you
