### ISSUE TITLE
Add support for Newrelic via opencensus 

### ISSUE THREAD

**Issue by hsinghkalsi** [krakend/krakend-opencensus#53]
Add support for Newrelic via opencensus 

https://github.com/newrelic/newrelic-opencensus-exporter-go

**Comment by alombarte** [comment]
Hello,

Thank you for opening this issue. KrakenD has traditionally offered its telemetry integration through this OpenCensus component, which has provided reliable service for over six years, but it is now transitioning to the more modern and robust [OpenTelemetry framework](https://www.krakend.io/docs/telemetry/opentelemetry/) (and NewRelic is supported)

Due to a change in the industry, the OpenCensus integration is no longer maintained by its creators, and all efforts are focused on OpenTelemetry. KrakenD shifted to OTEL too.

Issues found with OTEL can be opened in the repository [krakend-otel](https://github.com/krakend/krakend-otel)

Thank you
